### ISSUE TITLE
Translation file / string not working

### ISSUE THREAD

**Issue by TheGranadilla** [mailjet/wordpress-mailjet-plugin-apiv3#322] opened 2022-04-15 09:20 UTC
Hi,

This part of the translation files seems to be broken. The string don't get translated.

French translation file, line 1028:

#: src/includes/SettingsPages/WooCommerceSettings.php:211
#: src/includes/SettingsPages/WooCommerceSettings.php:1049
msgid "We have sent the newsletter subscription confirmation link to you: "
msgstr ""
"Nous vous avons envoyé le lien de confirmation d’inscription à la "
"newsletter : "

Thanks!

**Comment by Dumorya** [comment] 2022-06-07 07:08
Hi, I have exactly the same problem. Would it be possible to fix this quickly please?

**Comment by oleksandr-mykhailenko** [comment] 2022-06-07 07:41
> Hi, I have exactly the same problem. Would it be possible to fix this quickly please?

Hello, could you please provide how it can be reproduced ? I'm participating in project and want to understand how to recreate the problem and them fix it

**Comment by Dumorya** [comment] 2022-06-07 07:53
You need to order something, and then on the thank you page there will be this untranslated string.
Actually, to fix it, I used the following code, but I think it should be fixed by the plugin itself:

```
function change_text( $translated_text, $text, $domain )
{
    switch ( $translated_text )
    {
        case "We have sent the newsletter subscription confirmation link to you: " :
            $translated_text = 'Nous venons de vous envoyer un lien de confirmation d\'inscription à la newsletter à l\'adresse suivante: ';
            break;
        case "To confirm your subscription you have to click on the provided link." :
            $translated_text = 'Pour confirmer votre inscription, vous devez cliquer sur le lien fourni.';
            break;
    }
    
    return $translated_text;
}
add_filter( 'gettext', 'change_text', 20, 3 );
```

**Comment by oleksandr-mykhailenko** [comment] 2022-06-07 08:30
> You need to order something, and then on the thank you page there will be this untranslated string. Actually, to fix it, I used the following code, but I think it should be fixed by the plugin itself:
> 
> ```
> function change_text( $translated_text, $text, $domain )
> {
>     switch ( $translated_text )
>     {
>         case "We have sent the newsletter subscription confirmation link to you: " :
>             $translated_text = 'Nous venons de vous envoyer un lien de confirmation d\'inscription à la newsletter à l\'adresse suivante: ';
>             break;
>         case "To confirm your subscription you have to click on the provided link." :
>             $translated_text = 'Pour confirmer votre inscription, vous devez cliquer sur le lien fourni.';
>             break;
>     }
>     
>     return $translated_text;
> }
> add_filter( 'gettext', 'change_text', 20, 3 );
> ```

Thank you, I will work on that. Yep, for sure. Plugin will be updated soon

**Comment by oleksandr-mykhailenko** [comment] 2022-06-07 21:59
> Hi, I have exactly the same problem. Would it be possible to fix this quickly please?

Hello. Here is PR that will be merged during Wednesday and plugin will be updated. The problem was not with translated string it's because off wrong code implementation.

**Comment by oleksandr-mykhailenko** [comment] 2022-06-08 08:08
@Dumorya @TheGranadilla Plugin was update and transaction are fixed

**Closed** 2022-06-08 08:12 UTC
