### ISSUE TITLE
Wrong language when submitting

### ISSUE THREAD

**Issue by BenMcarnolds** [mailjet/wordpress-mailjet-plugin-apiv3#288] opened 2020-10-08 08:48 UTC
I have an issue when I'm submitting form in english, I'm getting the message confirmation in the website main language, french, and I receive the confirmation mail in french as well. 
(example: When the language is EN, and while I submit I get "Email de confirmation d'inscription envoyé. Veuillez vérifier votre boîte mail et confirmer votre inscription.")
I'm using WPML as translation plugin.

I don't know if I did something wrong. How can I fix this ? Where does mailjet get the language ?

**Comment by Pavlico** [comment] 2021-07-23 13:56
Hi @BenMcarnolds does issue still exist? I suspect it is not related to module as i checked and language is fine

**Comment by Pavlico** [comment] 2021-09-13 09:17
Cant reproduce, no answer, closing

**Closed by Pavlico** 2021-09-13 09:17 UTC
